# Test-GeneratedLaunchers.ps1
#
# Prevent-ClaudeIssues writes PowerShell out of here-strings: the boot task, the
# admin launcher, and now Launch-Claude-NoGPU.ps1. None of that is ever parsed
# at build time, so a stray brace or a backtick that was meant to escape and
# did not would ship silently and only surface when a user double-clicks it.
#
# The NoGPU launcher is a here-string inside a here-string, near enough: it
# interpolates $ToolkitVersion and the discovered package identity while
# escaping the runtime variables with backticks. That is exactly the shape that
# gets it wrong. So build it here the way the script builds it, and parse it.
#
# Also asserts the identity is interpolated rather than hardcoded. Writing
# Claude_pzs8sxrjxfjjc into the source would work on the machine this was
# written on and nowhere else, which is the bug the discovery layer exists to
# prevent and which has been reintroduced by hand once already.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root    = Split-Path -Parent $PSScriptRoot
$srcPath = Join-Path $root 'Prevent-ClaudeIssues.ps1'

$script:pass = 0
$script:fail = 0
function Assert {
    param([string]$Label, [bool]$Condition, [string]$Detail = '')
    if ($Condition) { Write-Host "  PASS  $Label" -ForegroundColor Green; $script:pass++ }
    else { Write-Host "  FAIL  $Label  $Detail" -ForegroundColor Red; $script:fail++ }
}

function Test-Parses {
    param([string]$Label, [string]$Code)
    $errors = $null
    $null = [System.Management.Automation.Language.Parser]::ParseInput($Code, [ref]$null, [ref]$errors)
    $n = @($errors).Count
    Assert $Label ($n -eq 0) $(if ($n) { $errors[0].Message } else { '' })
}

# ------------------------------------------------------------------
# Rebuild the generated launcher the way the script does, for both install
# shapes, and parse the result.
# ------------------------------------------------------------------
$ToolkitVersion = '0.0.0-test'

foreach ($case in @(
    @{ Name = 'MSIX install'
       Body = @"
Invoke-CommandInDesktopPackage ``
    -PackageFamilyName 'Claude_pzs8sxrjxfjjc' ``
    -AppId 'Claude' ``
    -Command 'app\Claude.exe' ``
    -Args '--disable-gpu'
"@
       Note = 'MSIX install, launching inside package identity (Claude_pzs8sxrjxfjjc)' }
    @{ Name = 'Traditional install'
       Body = "Start-Process -FilePath 'C:\Program Files\Claude\Claude.exe' -ArgumentList '--disable-gpu'"
       Note = 'Traditional install, flag passed directly' }
)) {
    Write-Host ""
    Write-Host "--- generated launcher: $($case.Name)" -ForegroundColor Cyan

    $launchBody = $case.Body
    $howNote    = $case.Note

    # Verbatim copy of the here-string in Prevent-ClaudeIssues step 27. If that
    # one changes, this has to change with it, and the parse below is what
    # catches the mistake either way.
    $ps1Content = @"
# Launch-Claude-NoGPU.ps1
# Auto-generated by Prevent-ClaudeIssues.ps1 v$ToolkitVersion
#
# $howNote

`$ErrorActionPreference = 'Stop'

`$running = @(Get-Process claude -ErrorAction SilentlyContinue)
if (`$running.Count -gt 0) {
    Write-Host "  Closing `$(`$running.Count) running Claude process(es)..." -ForegroundColor DarkGray
    `$running | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 3
}

Write-Host "  Starting Claude with --disable-gpu..." -ForegroundColor Cyan
$launchBody

Start-Sleep -Seconds 3
if (@(Get-Process claude -ErrorAction SilentlyContinue).Count -gt 0) {
    Write-Host "  Claude is running without hardware GPU acceleration." -ForegroundColor Green
} else {
    Write-Host "  [!] Claude did not start." -ForegroundColor Red
    Read-Host "  Press Enter to close"
}
"@

    Test-Parses "the generated script parses" $ps1Content

    # The runtime variables must survive as literal $ in the output, not be
    # expanded away at generation time. If the backticks were dropped,
    # $running would interpolate to nothing and the guard would be dead code.
    Assert "runtime `$running survived as a variable" ($ps1Content -match '\$running\.Count')
    Assert "runtime `$ErrorActionPreference survived"  ($ps1Content -match '\$ErrorActionPreference')
    Assert "the version WAS interpolated"             ($ps1Content -match [regex]::Escape($ToolkitVersion))
    Assert "the launch body was inlined"              ($ps1Content -match 'disable-gpu')
}

# ------------------------------------------------------------------
Write-Host ""
Write-Host "--- source does not hardcode this machine's install" -ForegroundColor Cyan
$src = [System.IO.File]::ReadAllText($srcPath)

# The literal package family of the machine this was developed on. Allowed in
# comments, never in code.
$codeLines = @($src -split "`r?`n" | Where-Object { $_ -notmatch '^\s*#' })
$hardcoded = @($codeLines | Where-Object { $_ -match 'Claude_pzs8sxrjxfjjc' })
Assert "no hardcoded package family in code" ($hardcoded.Count -eq 0) ($hardcoded -join ' | ')

Assert "the launcher reads PackageFamilyName from discovery" `
    ($src -match '\$script:ClaudeEnv\.PackageFamilyName')
Assert "the launcher reads ApplicationId from discovery" `
    ($src -match '\$script:ClaudeEnv\.ApplicationId')

# Undo has to take back everything setup puts down, or a user who reverts is
# left with a desktop shortcut pointing at a script nothing maintains.
Assert "Undo removes Launch-Claude-NoGPU.ps1"  ($src -match 'Launch-Claude-NoGPU\.ps1')
Assert "Undo removes Launch-Claude-NoGPU.cmd"  ($src -match 'Launch-Claude-NoGPU\.cmd')
Assert "Undo removes the desktop shortcut"     ($src -match 'Claude \(no GPU\)\.lnk')

# Step numbering has to agree with the declared total, or the progress display
# reads "Step 27 of 26".
$declared = [regex]::Match($src, '(?m)^\s*\$steps\s*=\s*(\d+)\s*$\s*[\s\S]{0,4000}?Step 1 \$steps "Configuring power plan')
$maxStep  = 0
foreach ($m in [regex]::Matches($src, '(?m)^\s*Step (\d+) \$steps')) {
    $v = [int]$m.Groups[1].Value
    if ($v -gt $maxStep) { $maxStep = $v }
}
$totals = @([regex]::Matches($src, '(?m)^\s*\$steps = (\d+)') | ForEach-Object { [int]$_.Groups[1].Value })
Assert "highest step number matches a declared total" `
    ($totals -contains $maxStep) "max step $maxStep, declared totals $($totals -join ', ')"

Write-Host ""
Write-Host "Generated launchers: $script:pass passed, $script:fail failed"
if ($script:fail -gt 0) {
    Write-Host "Generated launcher gate FAILED" -ForegroundColor Red
    exit 1
}
Write-Host "Generated launcher gate PASSED" -ForegroundColor Green
exit 0
